# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ccca21353be7629023abe01640ef35800efce1b41820ab2d9158b401444e30ae75f374cfa7aa1c44ac151d63f34a1ee364758ed8a9570d85dfc071530a8a545

test:
  secret_key_base: 4e7be3978b8e3f97ddbcd5ad75b1e34a69892f97b5bc26db4b943b2c7938e6629f9c45254c070ddc2607f490833c9ed8934b5cad34c8fd64340b1f733bc3d2a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
